### PR TITLE
fix modulo zero

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Modulo zero is not allowed and results in an arithmetic error.

This is the first error I hit on my system with the example `1_resource`. The dev branch is still not working on my laptop but this fixes one problem, other are under investigation.

### CODE REVIEW

**Review by michaelsippel — COMMENTED** [review]
If `n_workers` is `0` , we shouldnt be able to create an Allocator since the default constructor shall give the allocator of the current worker.       Now that `worker_id`  is initialized with `0` even though `n_workers` is also zero  will cause an invalid memory access whenever `allocate`  is called because  the vector containing the allocators ( in `WorkerPool` ) does not have `0` as a valid index

**Comment by psychocoderHPC** [comment]
The reason why I run into the issue I tried to fix with this PR is #47. The example was not implemented correctly.

**Comment by psychocoderHPC** [comment]
I set this PR for now to `draft` maybe it is not required anymore.

**Comment by psychocoderHPC** [comment]
not required it was solved with #47

**Pull request closed without merging**
